ALTER TABLE strategy_templates
  ALTER COLUMN created_at TYPE TIMESTAMPTZ USING (created_at AT TIME ZONE 'UTC'),
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING (updated_at AT TIME ZONE 'UTC');

ALTER TABLE backtest_runs
  ALTER COLUMN created_at TYPE TIMESTAMPTZ USING (created_at AT TIME ZONE 'UTC'),
  ALTER COLUMN started_at TYPE TIMESTAMPTZ USING (started_at AT TIME ZONE 'UTC'),
  ALTER COLUMN finished_at TYPE TIMESTAMPTZ USING (finished_at AT TIME ZONE 'UTC'),
  ALTER COLUMN from_ts TYPE TIMESTAMPTZ USING (from_ts AT TIME ZONE 'UTC'),
  ALTER COLUMN to_ts TYPE TIMESTAMPTZ USING (to_ts AT TIME ZONE 'UTC'),
  ALTER COLUMN cancel_requested_at TYPE TIMESTAMPTZ USING (cancel_requested_at AT TIME ZONE 'UTC'),
  ALTER COLUMN lease_until TYPE TIMESTAMPTZ USING (lease_until AT TIME ZONE 'UTC');
