const aiSettings = {
  ai: {
    settings: {
      pageTitle: 'AI アシスタント設定',
      defaultProfileName: 'デフォルト',
      primary: { title: 'デフォルト主モデル', hint: '意図明確化、コード生成などに使用。', placeholder: 'プロバイダー・モデルを選択してください' },
      tabs: { config: 'モデル設定', agents: 'エージェント設定' },
      fields: { name: '名前', provider: 'AIプロバイダー', baseUrl: '基底 URL', baseUrlHint: '（モデルサービスアドレス）', apiKey: 'API キー', apiKeyConfigured: '設定済', apiKeyReplaceHint: '交換する場合は再入力', deleteApiKey: 'キー削除', モデル: 'モデル', defaultModel: 'デフォルトモデル', availableModels: '利用可能モデル', availableModelsHint: '複数モデルを有効化可能。', availableModelsPlaceholder: '選択または入力', availableModelsEmpty: 'モデル IDを入力', availableModelsTip: '削除してもバインド済みエージェントは残ります。', clear: 'クリア', temperature: '温度', timeoutSeconds: 'タイムアウト秒数', maxTokens: '最大 トークン 数', enabledStatus: '有効状態', enabledOn: '有効→無効化', enabledOff: '無効→有効化' },
      sections: { basic: '基本情報', connection: '接続設定', advanced: '高度パラメータ', advancedHint: '意味を理解して調整。', connectionApiKeyLink: 'API キー申請/管理へ' },
      inferenceParams: { title: '推論パラメータ' },
      providers: { enabledTitle: '有効プロバイダー', emptyTitle: '有効プロバイダーなし', emptyHint: '', emptyHintTail: 'でAPI キーとモデルを設定。', modelsUnit: 'モデル', noModels: 'モデル未設定', openai: 'OpenAI', anthropic: 'Anthropic Claude', deepseek: 'DeepSeek', zhipu: 'Zhipu AI', qwen: 'Tongyi Qianwen', moonshot: 'Moonshot (Kimi)', doubao: 'Doubao', siliconflow: 'SiliconFlow', openrouter: 'OpenRouter', mistral: 'Mistral', groq: 'Groq', custom: 'カスタム（OpenAI互換）', openai_compatible: 'カスタム（OpenAI互換）' },
      placeholders: { name: '例: DeepSeek-低コスト', provider: 'AIプロバイダー選択', baseUrl: '例: https://api.example.com/v1', apiKey: 'API キー入力', providerFirst: '先にプロバイダー選択', modelManual: 'モデル名入力', modelSelect: 'モデル選択', modelSelectOrType: '選択または入力' },
      apiKeySavedAs: '現在保存済: {{masked}}',
      apiKeyGuide: { title: 'API キー申請ガイド', selectProviderHint: 'プロバイダー選択後、申請方法を表示。', modelSuggestionZhipu: 'モデル提案: glm-4-flash / glm-4', modelSuggestionDeepSeek: 'モデル提案: deepseek-chat', default: 'provider: {{provider}}。コンソールでAPI キー作成。', zhipu: { title: 'Zhipu API キー取得方法', step1: 'Zhipuプラットフォーム:', step2: 'ログイン/登録後、コンソールでAPI キー作成。' }, deepseek: { title: 'DeepSeek API キー取得方法', step1: 'DeepSeekプラットフォーム:', step2: 'ログイン/登録後、APIキー管理画面で作成。' } },
      actions: { validateApiKey: 'API キー検証', saveConfig: '設定保存' },
      profiles: { current: '現在', actions: { setCurrent: '現在に設定' }, delete: { title: '設定削除', content: '削除しますか？' } },
      messages: { loadConfigFailed: 'AI設定読込失敗', probeSuccess: '接続成功', probeFailed: '接続失敗', selectSavedProfileOrEnterKey: '保存済設定選択またはKey入力', validateSuccess: '検証成功', validateFailed: '検証失敗', apiKeyValidated: 'API キー検証成功', validateBeforeSave: '先に「API キー検証」をクリック', saveSuccess: '設定保存成功', deleted: '削除済', setCurrentSuccess: '現在設定切替', enabled: '有効化', disabled: '無効化' },
      errors: { arrearage: '残高不足。コンソールで確認。', invalidModelId: 'モデル利用不可{{model}}。', unauthorized: 'API キー無効（401）。', forbidden: 'アクセス拒否（403）。', timeout: '接続タイムアウト。' },
      discoverErrors: { baseUrlRequired: '先に Base URL（モデルサービスURL）を入力してください。', baseUrlInvalid: 'Base URL が無効です。例: https://model.example.com または https://model.example.com/v1', freeTierExhausted: '無料枠を使い切りました。コンソールで設定を確認するか有料キーに切り替えてください。', quotaOrRateLimit: 'クォータまたはレート制限です。課金/制限を確認するか後で再試行してください。', quotaForbidden403: '呼び出し拒否（クォータ）: コンソールの課金/クォータを確認してください。', unauthorized: '認証失敗: API キー/シークレットを確認してください。', endpoint404: 'エンドポイントが見つかりません: Base URL とプロトコル（/v1 など）を確認してください。', timeout: 'タイムアウト: ネットワークを確認するか後で再試行してください。', unreachable: 'モデルサービスに接続できません: Base URL・ネットワーク・ゲートウェイを確認してください。', invalidModelsResponse: '/models 互換ではない応答形式です。', noModelsReturned: '利用可能なモデルがありません。権限と設定を確認してください。', providerRegionBlocked: '地域制限: プロバイダーが検出された地域からの利用を拒否しました（出口IPはサーバ所在地と一致しない場合があります）。対応リージョンへの出口移行、準拠した HTTP(S) プロキシ、別プロバイダーへの切替を検討してください。', generic: 'モデル一覧の取得に失敗しました。Base URL と API キーを確認してください。', genericDetail: 'モデル一覧の取得に失敗: {{detail}}' },
      validation: { nameRequired: '名前必須', apiKeyRequired: 'API キー必須', baseUrlRequired: '基底 URL必須', baseUrlProtocol: 'http://またはhttps://で開始', baseUrlNoChatCompletionsSuffix: '/chat/completionsで終了不可', modelRequired: 'モデル必須', modelFormat: 'モデル形式不正' },
      agent: { title: 'エージェント身分定義', defaultName: 'カスタムエージェント', removeConfirmTitle: 'エージェント削除', removeConfirmContent: '削除しますか？', actions: { add: '追加', save: '保存', remove: '削除', loadDefaults: 'デフォルト8エージェント読込', restoreDefaults: 'デフォルト復元', restoreDefaultsConfirmTitle: 'システムデフォルト復元？', restoreDefaultsConfirmContent: '8システムエージェントをデフォルトにリセット。カスタムは保持。' }, messages: { selectProfileFirst: '先に左で設定選択', loading: '読込中…', empty: 'カスタムエージェントなし。「追加」で設定。', saveSuccess: 'エージェント保存', saveFailed: '保存失敗', defaultsLoaded: 'デフォルトテンプレート読込。「保存」で確定。' }, fields: { namePlaceholder: 'エージェント名', identityPlaceholder: '身分/人物設定記述', inputHintPlaceholder: '入力ヒント', modelProfilePlaceholder: 'デフォルト', modelProfileEmpty: '先に「AI設定」でプロバイダー/モデルを有効化' }, types: { style: 'スタイル/パラダイム', signals: 'シグナル/指標', risk: 'リスク', macro: 'マクロ', sentiment: 'センチメント', portfolio: 'ポートフォリオ', execution: '実行', code: 'コード' }, defaults: { style: { identity: '資深量化戦略アナリスト。戦略パラダイム選定。', inputHint: '例: アカウント=EURUSD小売、時間枠=H1、目標=月収益3%、DD<10%' }, signals: { identity: '量化因子・シグナルエンジニア。MA/EMA/RSI/MACD/ADX/ATR等。', inputHint: '例: パラダイム=トレンドフォロー、時間枠=H1、指標=EMA/ATR/ADX' }, risk: { identity: '取引リスク・実行専門家。ポジション管理、SL/TP、DD制御等。', inputHint: '例: 資産=10,000、許容DD=5%、取引リスク=0.5%、最大取引=5' }, macro: { identity: 'マクロリサーチャー。中央銀行金利、CPI/PPI、NFP、PMI、GDP等。', inputHint: '例: 今週重要イベント=米CPI（木20:30）、FOMC議事録（水翌02:00）' }, sentiment: { identity: '市場センチメント・資金フローアナリスト。COT、VIX、恐怖強欲指数等。', inputHint: '例: VIX 14→22、非商業純ロング-18%、ニュース「リセッション/利下げ」' }, portfolio: { identity: 'ポートフォリオ管理専門家。相関マトリックス、リスクパリティ、ボラターゲット等。', inputHint: '例: 既存戦略=トレンド-EURUSD、平均回帰-XAUUSD、総資産=50,000' }, execution: { identity: '実行・取引コスト最適化専門家。市指/指値/TWAP/VWAP/氷山等。', inputHint: '例: 注文=EURUSDロング10ロット、スプレッド=0.6pip、目標5分、許容スリッページ=0.8pip' }, code: { identity: 'AntTrader Pythonコードエンジニア。サンドボックス制約厳守。', inputHint: '例: パラダイム=トレンドフォロー、指標=EMA(fast)/EMA(slow)+ATRフィルタ' } } },
    },
  },
} as const;

export default aiSettings;
