const aiWizard = {
  ai: {
    wizard: {
      title: 'AI 戦略ウィザード',
      subtitle: '1ページ1ステップ',
      currentModel: '現在のモデル: {{model}}',
      rangePresets: { '1d': '最近 1 日', '3d': '最近 3 日', '7d': '最近 1 週', '30d': '最近 1 月', '90d': '最近 3 月' },
      steps: { setup: '基本情報', generate: '戦略生成', publishCode: 'バックテスト・公開-コード', publishBacktest: 'バックテスト・公開-バックテスト', publishLaunch: 'バックテスト・公開-公開' },
      actions: { prev: '戻る', next: '次へ', cancel: 'キャンセル' },
      generate: { cards: { resultsTitle: '複数専門家の結果' }, actions: { runAgents: '複数専門家分析 + コード生成', hide: '隠す', abort: '中止', rerun: '再生成', regenerateSummary: '要約再生成', goValidate: '検証へ' }, hints: { afterGenerated: '生成後、検証/バックテスト/公開へ' }, labels: { elapsed: '経過時間' }, status: { inProgress: '進行中', done: '完了', error: 'エラー', idle: '待機中', running: { style: '進行中', signals: '進行中', risk: '進行中', code: '進行中', generic: '{{title}}進行中' } }, sections: { prompt: 'Prompt', output: 'Output', spec: 'Spec' }, modals: { final: { title: 'コード生成完了。検証を推奨。' } } },
      publish: { cards: { codeTitle: '1) コード', scoreCardTitle: '2) スコアカード', launchTitle: '3) 公開スケジュール' }, placeholders: { codeEditable: 'AI生成コードがここに表示されます。' }, actions: { validateCode: 'コード検証', startBacktest: 'バックテスト', publishTemplate: 'テンプレート公開' }, messages: { validateOk: '検証合格', validateFailed: '検証不合格' } },
      agents: { styleTitle: '市場状況/スタイル', signalsTitle: 'シグナル/指標', riskTitle: 'リスク管理', codeTitle: 'コード生成' },
      template: { defaultName: 'AI戦略 {{title}}', defaultDescription: 'AI生成' },
      schedule: { defaultName: 'AIスケジュール {{symbol}} {{timeframe}}' },
      setup: { cards: { tradeAndDataTitle: '取引とデータ', constraintsAndGoalTitle: '制約と目標', hardConstraintsTitle: 'ハード制約', hintsTitle: 'ヒント' }, labels: { account: 'アカウント', symbol: '銘柄', timeframe: '時間枠', historicalData: '履歴データ', backtestRange: 'バックテスト範囲', dataset: 'データセット', maxDrawdownPct: '最大DD(%)', riskPerTradePct: '取引リスク(%)', maxTradesPerDay: '1日最大取引数', macroModule: 'マクロモジュール', macroEvents: 'マクロイベント', intent: '戦略目標/アイデア' }, placeholders: { selectAccount: 'アカウント選択', selectSymbol: '銘柄選択', selectTimeframe: '時間枠選択', selectFrozenDataset: 'データセット選択', macroExample: '例:\n2024-01-03 FOMC\n2024-01-05 NFP', intentExample: '例: トレンドフォロー、高ボラ回避、高勝率重視' }, validations: { selectAccount: 'アカウントを選択', selectSymbol: '銘柄を選択', selectTimeframe: '時間枠を選択', selectDataset: 'データセットを選択', enterIntent: '戦略目標を入力' }, dataModes: { klineRange: '履歴K線', dataset: 'データセット' }, actions: { refreshDataset: '更新', freezeFromCurrentRange: '現在範囲から凍結', deleteCurrentDataset: '現在データセット削除' }, modals: { deleteDataset: { title: 'データセット削除', content: '選択した凍結データセットを削除しますか？', ok: '削除' } }, messages: { datasetDeleted: 'データセット削除済' }, macro: { off: 'OFF', on: 'ON' }, hints: { nextWillGenerateCode: '次でコード生成開始。', tradeDataNextStep: '完了後「次へ」。' } },
      publishBacktest: { cards: { backtestTitle: 'バックテスト', scoreCardTitle: 'スコアカード' }, actions: { startBacktest: '開始', close: '閉じる', retry: '再試行', succeeded: '成功', inProgress: '進行中', runInBackground: 'バックグラウンド実行', confirm: '確認' }, labels: { status: '状態', elapsed: '経過', scoringProgress: '進捗', overallScore: '総合スコア', confirmed: '確認済' }, modals: { status: { title: 'バックテスト進行中' }, score: { title: 'スコア確認' } }, draftName: 'バックテスト {{datetime}} {{symbol}} {{timeframe}}', draftNameShort: 'バックテスト {{symbol}} {{timeframe}}' },
      strategyParams: { title: '戦略パラメータ（任意）', hints: { intro: 'これらのパラメータは:', line1: '1) テンプレートに保存', line2: '2) スケジュールに書き込み', line3Prefix: '3) Pythonに注入' }, actions: { addParam: '追加', exportJson: 'JSON出力', importJson: 'JSON入力', delete: '削除' }, empty: 'パラメータなし。', paramCardTitle: 'パラメータ #{{index}}', labels: { name: 'name', type: 'type', value: 'value', default: 'default', min: 'min', max: 'max', step: 'step', label: 'label', description: 'description', options: 'options' }, validations: { nameRequired: 'name必須', typeRequired: 'type必須' }, placeholders: { nameExample: '例: fast', value: '空欄でdefault使用', defaultExample: '例: 10', label: '表示名', description: '説明', optionsExample: '例: low,medium,high', importJson: 'JSON貼り付け' }, modals: { exportTitle: 'JSON出力', importTitle: 'JSON入力', copyAndClose: 'コピーして閉じる', importOk: '入力' }, messages: { jsonParseFailed: 'JSON解析失敗', importFormatInvalid: '形式エラー', importMissingName: 'name欠落', imported: '{{count}}個入力', copied: 'コピー済', copyFailed: 'コピー失敗' }, types: { number: '数値', string: '文字列', bool: '真偽値', select: '選択' } },
      prompts: { dataSpec: { dataset: 'データセット {{datasetId}}', klineRange: 'K線範囲 {{from}} - {{to}}' }, base: { account: 'アカウント: {{accountId}}', symbol: '銘柄: {{symbol}}', timeframe: '時間枠: {{timeframe}}', data: 'データ: {{dataSpec}}', constraints: '制約: DD={{maxDrawdownPct}}% リスク={{riskPerTradePct}}% 最大取引={{maxTradesPerDay}}', params: 'パラメータ:\n{{params}}', empty: '(空)', macroEnabled: 'マクロ:\n{{text}}', macroDisabled: 'マクロ: 未使用', userIntent: 'ユーザー意図:\n{{intent}}' }, upstream: { style: '【市場状況】\n{{text}}', signals: '【シグナル】\n{{text}}', risk: '【リスク】\n{{text}}', sectionTitle: '【上流エージェント結論】' }, summary: { intro: '戦略コードの核心を簡潔に説明してください。', mustIncludeTitle: '必須:', mustInclude1: '1) 戦略タイプ', mustInclude2: '2) 主要エントリー条件', mustInclude3: '3) 主要エグジット/リスク管理', mustInclude4: '4) 適用/非適用シナリオ', userIntent: 'ユーザー期待:\n{{intent}}', codeTitle: 'コード:' } },
      messages: { generateCodeFirst: 'まずコード生成', validateCodeFirst: 'まずコード検証', codeInvalidFixAndContinue: 'コード検証失敗', startBacktestFirst: 'まずバックテスト開始', backtestNotDoneWait: 'バックテスト完了待ち', confirmScoreFirst: 'まずスコア確認', fillRequiredWithFields: '必須項目入力: {{fields}}', fillRequired: '必須項目入力', watchBacktestRunFailed: 'watch失敗', createDraftFailed: 'ドラフト作成失敗', loadAccountsFailed: 'アカウント読込失敗', loadSymbolsFailed: '銘柄読込失敗', loadDatasetFailed: 'データセット読込失敗', datasetFrozenCreated: 'データセット凍結作成', freezeDatasetFailed: '凍結失敗', inputIntentFirst: 'まず戦略目標入力', aiRequestTimeout: 'タイムアウト', modelReturnedEmpty: '空返答', noPythonCodeBlock: 'コードブロックなし', agentFailed: '{{title}}失敗', userAborted: '中止', chatAborted: '中止', noCodeToValidate: '検証するコードなし', validateOk: '検証合格', validateFailed: '検証不合格', validateError: '検証エラー', noCodeToBacktest: 'バックテストするコードなし', backtestCreated: 'バックテスト作成', createBacktestFailed: '作成失敗', draftNotCreated: 'ドラフト未作成', draftSaved: 'ドラフト保存', saveFailed: '保存失敗', publishedNoId: '公開済（ID未取得）', templatePublished: 'テンプレート公開', publishFailed: '公開失敗', publishTemplateFirst: 'まずテンプレート公開', scheduleCreatedAndEnabled: 'スケジュール作成・有効化', scheduleCreated: 'スケジュール作成', createScheduleFailed: '作成失敗', scheduleAlreadyExists: '同じスケジュールが既に存在' },
    },
  },
} as const;

export default aiWizard;
