const aiSettings = {
  ai: {
    settings: {
      pageTitle: 'AI 助手設定',
      defaultProfileName: '預設',
      primary: { title: '預設主模型', hint: '用於「釐清意圖」步驟、程式碼生成等。', placeholder: '選擇廠商 · 模型作為兜底大腦' },
      tabs: { config: '模型設定', agents: '智能體 設定' },
      fields: { name: '名稱', provider: 'AI 提供商', baseUrl: '基礎網址', baseUrlHint: '（模型服務位址）', apiKey: 'API 金鑰', apiKeyConfigured: '已設定', apiKeyReplaceHint: '如需更換金鑰，請重新輸入', deleteApiKey: '刪除金鑰', 模型: '模型', defaultModel: '預設模型', availableModels: '可用模型', availableModelsHint: '同一 API 金鑰 下可同時啟用多個 模型。', availableModelsPlaceholder: '選擇或手動輸入 模型 ID', availableModelsEmpty: '直接輸入 模型 ID', availableModelsTip: '提示：刪除某個模型不會立即清空已繫結的 智能體。', clear: '清空', temperature: '溫度', timeoutSeconds: '逾時秒數', maxTokens: '最大 權杖 數', enabledStatus: '啟用狀態', enabledOn: '已啟用 → 點選關閉', enabledOff: '已停用 → 點選啟用' },
      sections: { basic: '基礎資訊', connection: '連線設定', advanced: '高階參數', advancedHint: '僅在瞭解含義時調整；預設值已適配大多數場景', connectionApiKeyLink: '前往申請 / 管理該廠商 API 金鑰' },
      inferenceParams: { title: '推理參數' },
      providers: { enabledTitle: '已啟用廠商', emptyTitle: '尚無啟用的廠商', emptyHint: '請先在 ', emptyHintTail: ' 設定 API 金鑰 與可用模型。', modelsUnit: '個模型', noModels: '未設定可用模型', openai: 'OpenAI', anthropic: 'Anthropic Claude', deepseek: 'DeepSeek', zhipu: '智譜 AI', qwen: '通義千問 / DashScope', moonshot: '月之暗面 Moonshot (Kimi)', doubao: '豆包 Doubao', siliconflow: '矽基流動 SiliconFlow', openrouter: 'OpenRouter', mistral: 'Mistral', groq: 'Groq', custom: '自定義（OpenAI 相容）', openai_compatible: '自定義（OpenAI 相容）' },
      placeholders: { name: '例如：DeepSeek-低成本', provider: '選擇 AI 提供商', baseUrl: '例如：https://api.example.com/v1', apiKey: '輸入 API 金鑰', providerFirst: '請先選擇 AI 提供商', modelManual: '請輸入模型名稱', modelSelect: '請選擇模型', modelSelectOrType: '從下拉選擇，或直接輸入 模型 ID' },
      apiKeySavedAs: '目前已儲存：{{masked}}',
      apiKeyGuide: { title: '申請 API 金鑰 指引', selectProviderHint: '選擇一個 AI 提供商後，會在這裡顯示如何申請 API 金鑰。', modelSuggestionZhipu: '模型建議：`glm-4-flash` / `glm-4`', modelSuggestionDeepSeek: '模型建議：`deepseek-chat`', default: '目前 廠商：{{provider}}。請到該服務商官網控制檯建立 API 金鑰。', zhipu: { title: '如何獲取智譜 API 金鑰', step1: '開啟智譜開放平臺：', step2: '登入/註冊後進入控制檯，建立並複製 API 金鑰' }, deepseek: { title: '如何獲取 DeepSeek API 金鑰', step1: '開啟 DeepSeek 平臺：', step2: '登入/註冊後在 API 金鑰s 頁面建立並複製 API 金鑰' } },
      actions: { validateApiKey: '驗證 API 金鑰', saveConfig: '儲存設定' },
      profiles: { current: '目前', actions: { setCurrent: '設為目前' }, delete: { title: '刪除設定', content: '確定要刪除該設定嗎？' } },
      messages: { loadConfigFailed: '載入 AI 設定失敗', probeSuccess: '連線成功', probeFailed: '連線失敗', selectSavedProfileOrEnterKey: '請先選擇一個已儲存的設定，或輸入 API 金鑰', validateSuccess: '驗證成功', validateFailed: '驗證失敗', apiKeyValidated: 'API 金鑰 驗證成功', validateBeforeSave: '請先點選「驗證 API 金鑰」', saveSuccess: '設定儲存成功', deleted: '已刪除', setCurrentSuccess: '已切換目前設定', enabled: '已啟用', disabled: '已停用' },
      errors: { arrearage: '服務商返回：帳號欠費/餘額不足。請到服務商控制檯檢查。', invalidModelId: '服務商返回：模型不可用{{model}}。請從下拉列表選擇。', unauthorized: '服務商返回：API 金鑰無效（401）。請檢查 Key 是否正確。', forbidden: '服務商返回：訪問被拒絕（403）。請檢查 Key 權限。', timeout: '連線逾時。請檢查 基礎網址 是否可訪問。' },
      discoverErrors: { baseUrlRequired: '請先填寫 Base URL（模型服務位址）。', baseUrlInvalid: 'Base URL 格式無效：請填寫完整位址，例如 https://model.example.com 或 https://model.example.com/v1', freeTierExhausted: '免費額度已耗盡：請在廠商控制台關閉「僅使用免費檔」或更換付費 Key。', quotaOrRateLimit: '配額受限或被限流：廠商已拒絕呼叫，請檢查計費/速率限制或稍後重試。', quotaForbidden403: '呼叫被拒（配額受限）：請檢查廠商控制台的計費/配額狀態。', unauthorized: '鑑權失敗：請檢查 API Key/Secret 是否正確。', endpoint404: '模型端點不存在：請確認 Base URL 與服務協定相符（部分服務需要 /v1）。', timeout: '請求逾時：請檢查網路連通性或稍後重試。', unreachable: '無法連線到模型服務：請檢查 Base URL、網路或閘道。', invalidModelsResponse: '模型服務回傳格式不相容 /models 協定。', noModelsReturned: '模型服務未回傳可用模型，請檢查帳號權限或服務設定。', providerRegionBlocked: '地域不可用：模型服務商依偵測到的來源拒絕請求（出口 IP 可能與主機所在地不同）。可嘗試更換部署或出口網路、設定合規 HTTP(S) 代理，或改用其他廠商。', generic: '拉取模型失敗，請檢查 Base URL 與金鑰設定。', genericDetail: '拉取模型失敗：{{detail}}' },
      validation: { nameRequired: '名稱不能為空', apiKeyRequired: 'API 金鑰 不能為空', baseUrlRequired: '基礎網址 不能為空', baseUrlProtocol: '基礎網址 必須以 http:// 或 https:// 開頭', baseUrlNoChatCompletionsSuffix: '基礎網址 不要以 /chat/completions 結尾', modelRequired: '模型不能為空', modelFormat: '模型格式不正確' },
      agent: { title: '智能體 身份定義', defaultName: '自定義 智能體', removeConfirmTitle: '刪除 智能體', removeConfirmContent: '確定要刪除該 智能體 嗎？', actions: { add: '新增', save: '儲存', remove: '刪除', loadDefaults: '載入預設 8 個 智能體', restoreDefaults: '恢復預設', restoreDefaultsConfirmTitle: '恢復系統預設身份？', restoreDefaultsConfirmContent: '將把 8 個系統 智能體 重置為預設身份定義。' }, messages: { selectProfileFirst: '請先在左側選擇一個設定', loading: '載入中...', empty: '暫無自定義 智能體，點選"新增"開始設定', saveSuccess: '智能體 已儲存', saveFailed: '智能體 儲存失敗', defaultsLoaded: '已載入系統預設 智能體 模板' }, fields: { namePlaceholder: '智能體 名稱', identityPlaceholder: '身份/人設描述', inputHintPlaceholder: '輸入提示（可選）', modelProfilePlaceholder: '預設（沿用目前設定檔）', modelProfileEmpty: '請先在「AI 設定」啟用至少一個 廠商/模型' }, types: { style: '風格/範式', signals: '訊號/指標', risk: '風控', macro: '巨集觀', sentiment: '情緒', portfolio: '組合', execution: '執行', code: '程式碼' }, defaults: { style: { identity: '你是資深量化策略分析師，專注於策略範式選型。', inputHint: '範例：帳戶=EURUSD 零售；週期=H1；目標=月均收益 3%、最大回撤 <10%' }, signals: { identity: '你是量化因子與訊號工程師，熟練使用 MA/EMA、RSI、MACD、ADX、ATR 等。', inputHint: '範例：範式=趨勢跟隨；週期=H1；可用指標=EMA/ATR/ADX' }, risk: { identity: '你是交易風險與執行約束專家。', inputHint: '範例：帳戶權益=10,000；可接受月回撤=5%；單筆風險=0.5%' }, macro: { identity: '你是巨集觀研究員，聚焦對短/中期價格有顯著影響的巨集觀事件。', inputHint: '範例：本週關鍵事件=美國 CPI（週四 20:30）' }, sentiment: { identity: '你是市場情緒與資金面分析師。', inputHint: '範例：近 1 週 VIX 從 14 升至 22' }, portfolio: { identity: '你是組合管理專家，負責多策略/多品種/多帳戶層面的資金分配。', inputHint: '範例：已有策略=趨勢-EURUSD、均值回歸-XAUUSD' }, execution: { identity: '你是執行與交易成本最佳化專家。', inputHint: '範例：訂單=做多 EURUSD 10 手；目前點差=0.6 pip' }, code: { identity: '你是 AntTrader Python 策略程式碼工程師。請生成可直接執行的策略程式碼，嚴格遵守沙箱校驗。', inputHint: '範例：目標範式=趨勢跟隨；指標=EMA(fast)/EMA(slow)+ATR 過濾' } } },
    },
  },
} as const;

export default aiSettings;
